name: ðŸ› Bug Report
description: Report a bug or unexpected behavior to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage", "type:bug"]
assignees:
  - tiatheone
body:
  - type: markdown
    attributes:
      value: |
        # ðŸ› Bug Report
        
        Thanks for taking the time to fill out this bug report! Your feedback helps us build a better product.
        
        > **ðŸ’¡ Tip**: The more details you provide, the faster we can reproduce and fix the issue.
        
        ---

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: "e.g., v1.2.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment is this happening in?
      options:
        - Development
        - Staging
        - Production
        - Local
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "e.g., Ubuntu 24.04, macOS 14.0, Windows 11"

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: What browser are you using?
      placeholder: "e.g., Chrome 120, Firefox 121, Safari 17"

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs to help explain your problem.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
