name: 📚 Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[DOCS] "
labels: ["documentation", "good first issue", "type:documentation"]
assignees:
  - tiatheone
body:
  - type: markdown
    attributes:
      value: |
        # 📚 Documentation Issue
        
        Help us improve our documentation to make it more helpful and accessible for everyone.
        
        > 📖 **Goal**: Clear, comprehensive, and up-to-date documentation is essential for project success.
        
        ---

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - API Documentation
        - Installation Guide
        - User Guide/Tutorial
        - Developer Guide
        - Contributing Guidelines
        - Code Comments
        - Wiki/Knowledge Base
        - Examples/Samples
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing Information
        - Outdated/Incorrect Information
        - Unclear/Confusing Content
        - Broken Links
        - Grammar/Spelling
        - Structure/Organization
        - Missing Examples
        - Translation Issue
        - Accessibility Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue in detail
      placeholder: What is wrong with the current documentation or what is missing?
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      placeholder: "e.g., README.md line 45, /docs/api/authentication.md, https://example.com/docs"

  - type: textarea
    id: current_content
    attributes:
      label: Current Content (if applicable)
      description: Quote the current documentation that needs to be changed
      placeholder: Paste the current content here...
      render: markdown

  - type: textarea
    id: suggested_content
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Provide suggested content, corrections, or improvements...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation fix?
      options:
        - Low - Minor improvement
        - Medium - Important for user experience
        - High - Blocking or misleading users
        - Critical - Security or safety concern
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - End Users
        - Developers/Contributors
        - System Administrators
        - API Consumers
        - New Contributors
        - All Users
        - Other

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Include screenshots, links to related issues, or examples of good documentation

  - type: checkboxes
    id: checklist
    attributes:
      label: Documentation Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have checked multiple pages/sections to understand the scope
          required: false
        - label: I am willing to help improve this documentation if guided
          required: false
        - label: I agree to follow this project's Code of Conduct
          required: true
